#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

host = data.get("host")
KC_HOSTNAME = f"https://{host}"

KEYCLOAK_ADMIN = data.get("KEYCLOAK_ADMIN", "admin")
KEYCLOAK_ADMIN_PASSWORD = data.get("KEYCLOAK_ADMIN_PASSWORD", "admin")
KC_HOSTNAME_STRICT_BACKCHANNEL = data.get("KC_HOSTNAME_STRICT_BACKCHANNEL", "true")
KC_HEALTH_ENABLED = data.get("KC_HEALTH_ENABLED", "true")
KC_LOG_LEVEL = data.get("KC_LOG_LEVEL", "info")
keycloak = {
    "KC_HOSTNAME": KC_HOSTNAME,
    "KC_HOSTNAME_STRICT_BACKCHANNEL": KC_HOSTNAME_STRICT_BACKCHANNEL,
    "KEYCLOAK_ADMIN": KEYCLOAK_ADMIN,
    "KEYCLOAK_ADMIN_PASSWORD": KEYCLOAK_ADMIN_PASSWORD,
    "KC_HEALTH_ENABLED": KC_HEALTH_ENABLED,
    "KC_LOG_LEVEL": KC_LOG_LEVEL
}
agent.write_envfile("keycloak.env", keycloak)
#agent.dump_env()
